[project]
name = "pymxbi"
version = "0.3.3"
description = "Python interfaces and drivers for MXBI"
readme = "README.md"
authors = [{ name = "HuYang", email = "huyangcommit@gmail.com" }]
requires-python = ">=3.14"
dependencies = [
    "gpiozero>=2.0.1",
    "loguru>=0.7.3",
    "numpy>=2.4.1",
    "prompt-toolkit>=3.0.52",
    "pyaudio>=0.2.14",
    "pydantic>=2.12.5",
    "pyglet>=2.1.13",
    "pymotego>=0.1.5",
    "pyserial>=3.5",
    "rich>=14.2.0",
    "typer>=0.21.1",
]

[project.scripts]
pymxbi = "pymxbi.cli:main"

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"
